services:
  matching-routing-service-database:
    image: mysql:9.2.0
    container_name: matching-routing-service-database
    environment:
        MYSQL_DATABASE: matching_routing_service
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
    ports:
      - "3315:3306"
      
  profile-service-database:
    image: mysql:9.2.0
    container_name: profile-service-database
    environment:
        MYSQL_DATABASE: profile_service
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
    ports:
      - "3320:3306"
